title: Hoang Do's Porfolio
description: "Welcome to Hoang's portfolio, where you can explore my software engineering projects, technical skills, certifications, and contributions to real-world applications."
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
